<a href="https://colab.research.google.com/github/lilian-2021/DS/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
a = np.array([1,2,3,4,5])
type(a)


numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.ndim
a.shape
# returns a tuple showing the no. elements along each dimension

(5,)

In [ ]:
a.size
# returns the number of elements in the array(total number of elements)

5

In [ ]:
a =np.array([11,2,3,4])
f = np.array([1.2,2.3,4.5,5.6])
a
f
a+f


array([12.2,  4.3,  7.5,  9.6])

In [ ]:
a ** f

type(a)
a + 10

array([21, 12, 13, 14])

In [ ]:
# universal functions(ufuncs)
np.sin(a)
a[1] = 4
a

array([11,  4,  3,  4])

In [ ]:
# multi-Dimensional arrays
c = np.array([[0,1,2,3],[10,11,12,13]])
type(c)
c.ndim
c.shape
c.size
c[1,3] = -1
c
c[1]



array([10, 11, 12, -1])

In [ ]:
# slicing extracts a portion of a sequence by specifying a lower and upper bound.
# The lower bound element is included , but the upper-bound element is not included.
# the step value specifies the stride between elements.
a = np.array([10,11,12,13,14])
a[1:3]
a[1:-2]
a[-4:3]

array([11, 12])

In [ ]:
# ommitted boundaries are assumed to be the beginning (or end) of the list
# grab first three elements
a[:3]
# grab last two elements
a[:-2]
# every other element
a[::2]
a[::]
a[1::]
a[1::2]

array([11, 13])

In [ ]:
# Array slicing
# row 0 columns 3 to 5
a[0,3:5]
# throw away 4 columns and 4 rows
a[4:,4:]
# column selection
# all rows in column 2
a[:,2]
# strided
a[2::2, ::2]


In [ ]:
# create an array of 25 numbers and arrange them as a cube(5 rows,5 columns)
a = np.arange(25).reshape(5,5)
a

# all rows,jump column 1(shifted) and select all the other columns in intervals 0f 2
a[:,1::2]
# jump the first row(offset of one) and select all the other rows in intervals of 2, select all columns of those rows in intervals of 2
#Note: use double colons when there is an offset, use a single lonely colon to select everything
a[1::2,::2]

# jump the first 4 rows
a[4:]
# select row 4
a[4]
# select row 4 and all columns
a[4,:]
# select the last row and all columns
a[-1,:]
# jump the first row(offset of one) and select all the other rows .stop at index 4(not included)
a[1::2,:4:2]
a[1::2,:-1:2]
# jump the first row(offset of one) and select all the other rows . stop at index 3(not included)
a[1::2,:3:2]
a[1::2,:-2:2]


array([[ 5,  7],
       [15, 17]])

In [ ]:

# sharing memory. a view
a = np.array([1,2,3,4])
b = a[:2]
a
b
b[0]=-1
a
b = a[::]
b
# making a copy of an array(they are completely separate from each other. no memory buffer )
b = a.copy()
b
b[0]=9
b
a

array([-1,  2,  3,  4])

In [ ]:
# selecting the last two elements
a[-2:]
a[2:]
## selecting the first two elements
a[:2]

# insert an iterable of length 2
a[-2:]=[7,8]
a
# or a scalar value



array([-1,  2,  7,  8])

In [ ]:
# selecting the last two elements
a[-2:]
a[2:]
## selecting the first two elements
a[:2]

# insert an iterable of length 2
a[-2:]=[7,8]
a
# or a scalar value
a[-2:]=[99]
a


array([-1,  2, 99, 99])

In [ ]:
# Fancy indexing/masking/boolean indexing
# helps you to index by position and value
# takes two forms i.e indexing by position and with booleans(masking)
# an array from 0 to 80 upper bound not included in steps of 10
a = np.arange(0,80,10)
a
indices = [1,2,-3]
y = a[indices]
y
a[indices]=99
a
# indexing with boolean
mask = np.array([0,1,1,0,0,1,0,0], dtype=bool)
y = a[mask]
y


array([99, 99, 99])

In [ ]:
a = np.array([-1,-3,1,4,-6,9,3])
negative = a<0
a[negative]
a[negative]=0
a


array([0, 0, 1, 4, 0, 9, 3])

In [ ]:
#  fancy indexing in 2-D
# diagonal selection using indices instead of the diagonal numpy method
a=np.arange(0,125,5).reshape(5,5)
a[[0,1,2,3],[1,2,3,4]]
# selecting values with different step sizes fancy indexing comes to the rescue
a[3:,[0,1,4]]
# combining masking/boolean indexing with normal position indexing to get 'true rows' for column 2
mask = np.array([1,0,1,0,0],dtype=bool)
a[mask,2]
a


array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120]])

In [ ]:
# note: unlike slicing, fancy indexing creates copies instead of a view into original array
a[[0,1,2,3],[1,2,3,4]]
a[3:,[0,1,4]]
mask = np.array([1,0,1,0,0],dtype=bool)
a[mask,2]


array([10, 60])

In [ ]:
a = np.arange(25).reshape(5,5)
a
blue =[[0,2,3,3],[2,3,1,4]]
a[blue]
# using boolean mask to extract all numbers divisible by 3
a[a%3==0]
a%3==0




<ipython-input-55-2e94e3be1f74>:4: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  a[blue]


array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [ ]:
# note: numpy is row major unlike matlab and fortran which are column majors
# calculations using arrays
# rules:
# 1. Operations between multiple array objects are first checked for proper shape match
# 2. Mathematical operators (+-*/exp,log,...) apply element by element , on the values
# 3 Reduction operations(mean,std,skew,kurt,sum,prod,...) apply to the whole array,unless an axis is specified
# 4. Missing values propagate unless explicitly ignored(nanmean,nansum,...).

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.sum()
# sum along the 0 axis
a.sum(axis=0)
# sum along the last axis(last axis is always the column)
a.sum(axis =-1)

array([ 6, 15])

In [ ]:
a = np.ones((5,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# numpy's where function has two distinct uses.One is to provide coordinates from masks
a = np.array([-1,2,5,5])
a == a.max()
np.where(a == a.max())
np.where(a>0)
a =np.arange(-2,2)**2
a
mask = a%2 == 0
mask
# coordinates are returned as a tuple of arrays , one for each axis
np.where(mask)

(array([0, 2]),)

In [ ]:
# where can also be used to construct a new array by choosing values from other arrays of the same shape
positives = np.arange(4)
positives
negatives =- positives
negatives
np.where(mask,positives,negatives)
# or from scalar values
# This can be useful for recoding arrays
np.where(mask,1,0)
# or from both
np.where(mask,positives,negatives)

array([ 0, -1,  2, -3])

In [ ]:
# using loadtx to load a numpy array/data
from numpy import loadtxt
# data = loadtxt('wind.data')


FileNotFoundError: ignored